### ISSUE TITLE
Add a workflow to build an publish new image on every push to main

### ISSUE THREAD

**Issue by dmaretskyi** [EthWorks/hostlify#12]
Example:
```yaml
name: Release
on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: .....


```
