### ISSUE TITLE
Create github action for publishing

### ISSUE THREAD

**Issue by dmaretskyi** [EthWorks/hostlify#6]
https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action

In a separate repo `EthWorks/hostlify-publish`

Then in workflow yaml it will look like this:

```yaml
- uses: EthWorks/hostlify-publish
   with:
     files: ./frontend/build
     id: {{ github.COMMIT_SHA }}
```
